/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoso;

import java.util.concurrent.Semaphore;
import javax.swing.JLabel;

/**
 *
 * @author luismanzano
 * @author Leonardo Gonzalez
 */
public class PanelControl extends javax.swing.JFrame {
    
    /*
    Imports necesarios para actualizar la informacion en la interfaz grafica
    */
    Controlador control = new Controlador();
    
    
//    Productor_botones boton = new Productor_botones();
    
    private int cant_botones = Productor_botones.botones;
    private int almacen_botones = Productor_botones.almacen_botones;
    private int cant_productores_boton = Productor_botones.productores_botones;
    
//    Productor_pantallas pantalla = new Productor_pantallas();
    
    private int cant_pantallas_normales = Productor_pantallas.pantallas_normales;
    private int cant_pantallas_tactiles = Productor_pantallas.pantallas_tactiles;
    private int cant_prouctores_pantallas = Productor_pantallas.productores_pantallas;
    private int almacen_pantallas = Productor_pantallas.almacen_pantallas;
    
//    Productor_joysticks joysticks = new Productor_joysticks();
    
    private int cant_joysticks = Productor_joysticks.joysticks;
    private int almacen_joysticks = Productor_joysticks.almacen_joysticks;
    private int cant_productores_joysticks = Productor_joysticks.productores_joysticks;
    
//    Productor_SD SD = new Productor_SD();
    
    private int cant_sd = Productor_SD.SD;
    private int almacen_sd = Productor_SD.almacen_SD;
    private int cant_productores_sd = Productor_SD.productores_SD;
    
    //CANTIDAD CONSOLAS TERMINADAS
    
    private int cant_consolas = Ensamblador.consolas_listas;
    private int cant_ensambladores = Ensamblador.ensambladores;
    
    /**
     * Creates new form PanelControl
     */
    public PanelControl() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        duracionDia = new javax.swing.JSpinner();
        jTextField1 = new javax.swing.JTextField();
        startProgram = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cantBotonesText = new javax.swing.JLabel();
        cantPantallasText = new javax.swing.JLabel();
        cantPTactilText = new javax.swing.JLabel();
        cantJoystickText = new javax.swing.JLabel();
        cantSDText = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cantProductorBotones = new javax.swing.JLabel();
        cantProductorPantalla = new javax.swing.JLabel();
        cantProductorPTactil = new javax.swing.JLabel();
        cantProductorJoystick = new javax.swing.JLabel();
        cantProductorSD = new javax.swing.JLabel();
        consolasTerminadasText = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cantEnsambladorText = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        statusJefeText = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        statusGerenteText = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        diasLanzamientoText = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        almacenBoton = new javax.swing.JLabel();
        almacenPantalla = new javax.swing.JLabel();
        almacenPantallaTactil = new javax.swing.JLabel();
        almacenJoystick = new javax.swing.JLabel();
        almacenSD = new javax.swing.JLabel();
        stopProgram = new javax.swing.JButton();
        menosP_botones = new javax.swing.JButton();
        masP_botones = new javax.swing.JButton();
        masP_pantallas = new javax.swing.JButton();
        menosP_pantallas = new javax.swing.JButton();
        masP_joysticks = new javax.swing.JButton();
        menosP_joysticks = new javax.swing.JButton();
        masP_SD = new javax.swing.JButton();
        menosP_SD = new javax.swing.JButton();
        masEnsambladores = new javax.swing.JButton();
        menosEnsambladores = new javax.swing.JButton();
        reanudarPrograma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("Duracion del dia (ms)");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        startProgram.setText("Iniciar");
        startProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startProgramActionPerformed(evt);
            }
        });

        jLabel1.setText("Productores");

        jLabel2.setText("Botones");

        jLabel3.setText("Pantalla normal");

        jLabel4.setText("Pantalla tactil");

        jLabel5.setText("Joystick");

        jLabel6.setText("Tarjeta SD");

        jLabel7.setText("Producidos");

        cantBotonesText.setText("0");

        cantPantallasText.setText("0");

        cantPTactilText.setText("0");

        cantJoystickText.setText("0");

        cantSDText.setText("0");

        jLabel8.setText("Productores activos");

        cantProductorBotones.setText("0");
        cantProductorBotones.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cantProductorBotonesPropertyChange(evt);
            }
        });

        cantProductorPantalla.setText("0");

        cantProductorPTactil.setText("0");

        cantProductorJoystick.setText("0");

        cantProductorSD.setText("0");

        consolasTerminadasText.setText("0");

        jLabel9.setText("Consolas Terminadas:");

        jLabel10.setText("Cantidad Ensamblador");

        cantEnsambladorText.setText("0");

        jLabel11.setText("Status Jefe");

        statusJefeText.setText("n/a");

        jLabel12.setText("Status Gerente:");

        statusGerenteText.setText("n/a");

        jLabel13.setText("Dias para lanzamiento");

        diasLanzamientoText.setText("0");

        jLabel14.setText("Espacio en almacen");

        almacenBoton.setText("0");

        almacenPantalla.setText("0");

        almacenPantallaTactil.setText("0");

        almacenJoystick.setText("0");

        almacenSD.setText("0");

        stopProgram.setText("Detener");
        stopProgram.setEnabled(false);
        stopProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopProgramActionPerformed(evt);
            }
        });

        menosP_botones.setText("-");
        menosP_botones.setEnabled(false);
        menosP_botones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosP_botonesActionPerformed(evt);
            }
        });

        masP_botones.setText("+");
        masP_botones.setEnabled(false);
        masP_botones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masP_botonesActionPerformed(evt);
            }
        });

        masP_pantallas.setText("+");
        masP_pantallas.setEnabled(false);
        masP_pantallas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masP_pantallasActionPerformed(evt);
            }
        });

        menosP_pantallas.setText("-");
        menosP_pantallas.setEnabled(false);
        menosP_pantallas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosP_pantallasActionPerformed(evt);
            }
        });

        masP_joysticks.setText("+");
        masP_joysticks.setEnabled(false);
        masP_joysticks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masP_joysticksActionPerformed(evt);
            }
        });

        menosP_joysticks.setText("-");
        menosP_joysticks.setEnabled(false);
        menosP_joysticks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosP_joysticksActionPerformed(evt);
            }
        });

        masP_SD.setText("+");
        masP_SD.setEnabled(false);
        masP_SD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masP_SDActionPerformed(evt);
            }
        });

        menosP_SD.setText("-");
        menosP_SD.setEnabled(false);
        menosP_SD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosP_SDActionPerformed(evt);
            }
        });

        masEnsambladores.setText("+");
        masEnsambladores.setEnabled(false);
        masEnsambladores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masEnsambladoresActionPerformed(evt);
            }
        });

        menosEnsambladores.setText("-");
        menosEnsambladores.setEnabled(false);
        menosEnsambladores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosEnsambladoresActionPerformed(evt);
            }
        });

        reanudarPrograma.setText("Reanudar");
        reanudarPrograma.setEnabled(false);
        reanudarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reanudarProgramaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(menosP_botones, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(menosP_joysticks, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(menosP_SD, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(menosP_pantallas, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(masP_pantallas, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(masP_joysticks, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(masP_SD, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(masP_botones)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cantProductorSD)
                                            .addComponent(cantProductorJoystick)
                                            .addComponent(cantProductorPantalla)
                                            .addComponent(cantProductorPTactil)
                                            .addComponent(cantProductorBotones))
                                        .addGap(49, 49, 49)))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cantPTactilText)
                                    .addComponent(cantJoystickText)
                                    .addComponent(cantSDText)
                                    .addComponent(cantBotonesText, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cantPantallasText))
                                .addGap(60, 60, 60))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(startProgram)
                                        .addGap(32, 32, 32)
                                        .addComponent(reanudarPrograma)
                                        .addGap(36, 36, 36)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(duracionDia, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(diasLanzamientoText)
                                            .addComponent(jLabel7)))
                                    .addComponent(stopProgram, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(30, 30, 30)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(almacenSD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(almacenJoystick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(almacenPantallaTactil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(almacenBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(almacenPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel14))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cantEnsambladorText)
                                    .addComponent(consolasTerminadasText)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(menosEnsambladores)
                                .addGap(38, 38, 38)
                                .addComponent(masEnsambladores)
                                .addGap(11, 11, 11)))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(statusJefeText)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statusGerenteText)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(jLabel13)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duracionDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startProgram)
                    .addComponent(stopProgram)
                    .addComponent(reanudarPrograma))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(statusJefeText)
                    .addComponent(jLabel12)
                    .addComponent(statusGerenteText))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(diasLanzamientoText))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel14))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(cantEnsambladorText))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(masEnsambladores, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(menosEnsambladores, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cantProductorPTactil)
                                .addComponent(jLabel4)
                                .addComponent(cantPTactilText)
                                .addComponent(almacenPantallaTactil))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(masP_botones)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cantProductorBotones)
                                        .addComponent(cantBotonesText)
                                        .addComponent(almacenBoton)
                                        .addComponent(menosP_botones)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cantProductorPantalla)
                                    .addComponent(cantPantallasText)
                                    .addComponent(almacenPantalla))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(menosP_pantallas)
                                    .addComponent(masP_pantallas))
                                .addGap(13, 13, 13)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cantProductorJoystick)
                            .addComponent(cantJoystickText)
                            .addComponent(almacenJoystick)
                            .addComponent(masP_joysticks)
                            .addComponent(menosP_joysticks)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(consolasTerminadasText))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cantProductorSD)
                    .addComponent(cantSDText)
                    .addComponent(almacenSD)
                    .addComponent(masP_SD)
                    .addComponent(menosP_SD))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void startProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startProgramActionPerformed
                        // TODO add your handling code here:
                startProgram.setEnabled(false);
                stopProgram.setEnabled(true);
                
                statusJefeText.setText("Durmiendo");
                statusGerenteText.setText("Activo");
                
                cantProductorBotones.setText(Integer.toString(cant_productores_boton));
                cantBotonesText.setText(Integer.toString(cant_botones));
                almacenBoton.setText(Integer.toString(almacen_botones));
                
                cantProductorPantalla.setText(Integer.toString(cant_prouctores_pantallas));
                cantProductorPTactil.setText(Integer.toString(cant_prouctores_pantallas));
                cantPantallasText.setText(Integer.toString(cant_pantallas_normales));
                cantPTactilText.setText(Integer.toString(cant_pantallas_tactiles));
                almacenPantalla.setText(Integer.toString(almacen_pantallas));
                almacenPantallaTactil.setText(Integer.toString(almacen_pantallas));
                
                cantJoystickText.setText(Integer.toString(cant_joysticks));
                cantProductorJoystick.setText(Integer.toString(cant_productores_joysticks));
                almacenJoystick.setText(Integer.toString(almacen_joysticks));
                
                cantSDText.setText(Integer.toString(cant_sd));
                cantProductorSD.setText(Integer.toString(cant_productores_sd));
                almacenSD.setText(Integer.toString(almacen_sd));
                
                cantEnsambladorText.setText(Integer.toHexString(cant_ensambladores));
                consolasTerminadasText.setText(Integer.toString(cant_consolas));
                
                control.controlInicio();
    }//GEN-LAST:event_startProgramActionPerformed

    private void cantProductorBotonesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cantProductorBotonesPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cantProductorBotonesPropertyChange

    private void stopProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopProgramActionPerformed
        // TODO add your handling code here:

        reanudarPrograma.setEnabled(true);
        stopProgram.setEnabled(false);
        
        masP_botones.setEnabled(true);
        menosP_botones.setEnabled(true);
        
        masP_pantallas.setEnabled(true);
        menosP_pantallas.setEnabled(true);
        
        masP_joysticks.setEnabled(true);
        menosP_joysticks.setEnabled(true);
        
        masP_SD.setEnabled(true);
        menosP_SD.setEnabled(true);
        
        masEnsambladores.setEnabled(true);
        menosEnsambladores.setEnabled(true);
        
        control.controlDetener();
    }//GEN-LAST:event_stopProgramActionPerformed

    private void menosP_botonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosP_botonesActionPerformed
         // TODO add your handling code here:
         control.despedirP_botones();
        cantProductorBotones.setText(Integer.toString(Productor_botones.productores_botones));
    }//GEN-LAST:event_menosP_botonesActionPerformed

    private void masP_botonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masP_botonesActionPerformed
        // TODO add your handling code here:
        control.contratarP_botones();
        cantProductorBotones.setText(Integer.toString(Productor_botones.productores_botones));
    }//GEN-LAST:event_masP_botonesActionPerformed

   
    private void reanudarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reanudarProgramaActionPerformed
        // TODO add your handling code here:
        reanudarPrograma.setEnabled(false);
        stopProgram.setEnabled(true);
        
        masP_botones.setEnabled(false);
        menosP_botones.setEnabled(false);
        
        masP_pantallas.setEnabled(false);
        menosP_pantallas.setEnabled(false);
        
        masP_joysticks.setEnabled(false);
        menosP_joysticks.setEnabled(false);
        
        masP_SD.setEnabled(false);
        menosP_SD.setEnabled(false);
        
        masEnsambladores.setEnabled(false);
        menosEnsambladores.setEnabled(false);
        
        control.reanudar();
    }//GEN-LAST:event_reanudarProgramaActionPerformed

    private void masP_pantallasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masP_pantallasActionPerformed
        // TODO add your handling code here:
        control.contratarP_pantallas();
        cantProductorPantalla.setText(Integer.toString(Productor_pantallas.productores_pantallas));
        cantProductorPTactil.setText(Integer.toString(Productor_pantallas.productores_pantallas));
    }//GEN-LAST:event_masP_pantallasActionPerformed

    private void menosP_pantallasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosP_pantallasActionPerformed
        // TODO add your handling code here:
        control.despedirP_pantallas();
        cantProductorPantalla.setText(Integer.toString(Productor_pantallas.productores_pantallas));
        cantProductorPTactil.setText(Integer.toString(Productor_pantallas.productores_pantallas));
    }//GEN-LAST:event_menosP_pantallasActionPerformed

    private void masP_joysticksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masP_joysticksActionPerformed
        // TODO add your handling code here:
        control.contratarP_joysticks();
        cantProductorJoystick.setText(Integer.toString(Productor_joysticks.productores_joysticks));
    }//GEN-LAST:event_masP_joysticksActionPerformed

    private void menosP_joysticksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosP_joysticksActionPerformed
        // TODO add your handling code here:
        control.despedirP_joysticks();
        cantProductorJoystick.setText(Integer.toString(Productor_joysticks.productores_joysticks));
    }//GEN-LAST:event_menosP_joysticksActionPerformed

    private void masP_SDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masP_SDActionPerformed
        // TODO add your handling code here:
        control.contratarP_SD();
        cantProductorSD.setText(Integer.toString(Productor_SD.productores_SD));
    }//GEN-LAST:event_masP_SDActionPerformed

    private void menosP_SDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosP_SDActionPerformed
        // TODO add your handling code here:
        control.despedirP_SD();
        cantProductorSD.setText(Integer.toString(Productor_SD.productores_SD));
    }//GEN-LAST:event_menosP_SDActionPerformed

    private void masEnsambladoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masEnsambladoresActionPerformed
        // TODO add your handling code here:
        control.contratarEnsamblador();
        cantEnsambladorText.setText(Integer.toString(Ensamblador.ensambladores));
    }//GEN-LAST:event_masEnsambladoresActionPerformed

    private void menosEnsambladoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosEnsambladoresActionPerformed
        // TODO add your handling code here:
        control.despedirEnsamblador();
        cantEnsambladorText.setText(Integer.toString(Ensamblador.ensambladores));
    }//GEN-LAST:event_menosEnsambladoresActionPerformed

    /**
     * @param args the command line arguments
     */
     /*ELEMENTOS DEL MAIN*/
//    public static volatile int contador_global = 0;
     /*la cantidad de botones que se estan generando */
//    public static volatile int cantidad_botones = 0;
    
    /* Metodos para actualizar los labels en la interfaz */
    public static void setEstadisticaConsolas(String consolas){
        consolasTerminadasText.setText(consolas);
    }
  
    
    public static void setEstadisticaBotones(String botones, String almacen){
        cantBotonesText.setText(botones);
        almacenBoton.setText(almacen);
    }
    
    public static void setStatusJefe(String string){
        statusJefeText.setText(string);
    }
    
    public static void setStatusGerente(String string){
        statusGerenteText.setText(string);
    }
    
    public static void setEstadisticaPantallaNormal(String pantalla_normal , String almacen){
        cantPantallasText.setText(pantalla_normal);
        almacenPantalla.setText(almacen);
        almacenPantallaTactil.setText(almacen);
    }
    
    public static void setEstadisticaPantallaTactil(String pantalla_tactil , String almacen){
        cantPTactilText.setText(pantalla_tactil);
        almacenPantalla.setText(almacen);
        almacenPantallaTactil.setText(almacen);
    }
    
    public static void setEstadisticaDiasRestantes(String string ){
        diasLanzamientoText.setText(string);
    }
    
    public static void setEstadisticasJoysticks(String joysticks, String almacen){
        cantJoystickText.setText(joysticks);
        almacenJoystick.setText(almacen);
    }
    
    public static void setEstadisticasSD(String SD, String almacen){
        cantSDText.setText(SD);
        almacenSD.setText(almacen);
    }
    
   
    public static void setEstadisticasProductorBotones(String valor){
        cantProductorBotones.setText(valor);
    }
    
    public static void setEstadisticasProductorPantallas(String valor){
        cantProductorPantalla.setText(valor);
        cantProductorPTactil.setText(valor);
    }
    
    public static void setEstadisticasProductorJoysticks(String valor){
        cantProductorJoystick.setText(valor);
    }
    
    public static void setEstadisticasProductorSD(String valor){
        cantProductorSD.setText(valor);
    }
    
    public static void main(String args[]) {
         
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelControl().setVisible(true);
            }
        });
    
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel almacenBoton;
    private static javax.swing.JLabel almacenJoystick;
    private static javax.swing.JLabel almacenPantalla;
    private static javax.swing.JLabel almacenPantallaTactil;
    private static javax.swing.JLabel almacenSD;
    private static javax.swing.JLabel cantBotonesText;
    private static javax.swing.JLabel cantEnsambladorText;
    private static javax.swing.JLabel cantJoystickText;
    private static javax.swing.JLabel cantPTactilText;
    private static javax.swing.JLabel cantPantallasText;
    private static javax.swing.JLabel cantProductorBotones;
    private static javax.swing.JLabel cantProductorJoystick;
    private static javax.swing.JLabel cantProductorPTactil;
    private static javax.swing.JLabel cantProductorPantalla;
    private static javax.swing.JLabel cantProductorSD;
    private static javax.swing.JLabel cantSDText;
    private static javax.swing.JLabel consolasTerminadasText;
    private static javax.swing.JLabel diasLanzamientoText;
    private javax.swing.JSpinner duracionDia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton masEnsambladores;
    private javax.swing.JButton masP_SD;
    private javax.swing.JButton masP_botones;
    private javax.swing.JButton masP_joysticks;
    private javax.swing.JButton masP_pantallas;
    private javax.swing.JButton menosEnsambladores;
    private javax.swing.JButton menosP_SD;
    private javax.swing.JButton menosP_botones;
    private javax.swing.JButton menosP_joysticks;
    private javax.swing.JButton menosP_pantallas;
    private javax.swing.JButton reanudarPrograma;
    private javax.swing.JButton startProgram;
    private static javax.swing.JLabel statusGerenteText;
    private static javax.swing.JLabel statusJefeText;
    private javax.swing.JButton stopProgram;
    // End of variables declaration//GEN-END:variables
}
