/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoso;

import java.util.concurrent.Semaphore;

/**
 *
 * @author luismanzano
 */
public class PanelControl extends javax.swing.JFrame {
    
   

    /**
     * Creates new form PanelControl
     */
    public PanelControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        duracionDia = new javax.swing.JSpinner();
        jTextField1 = new javax.swing.JTextField();
        startProgram = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cantBotonesText = new javax.swing.JLabel();
        cantPantallasText = new javax.swing.JLabel();
        cantPTactilText = new javax.swing.JLabel();
        cantJoystickText = new javax.swing.JLabel();
        cantSDText = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cantProductorBotones = new javax.swing.JLabel();
        cantProductorPantalla = new javax.swing.JLabel();
        cantProductorPTactil = new javax.swing.JLabel();
        cantProductorJoystick = new javax.swing.JLabel();
        cantProductorSD = new javax.swing.JLabel();
        consolasTerminadasText = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cantEnsambladorText = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        statusJefeText = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        statusGerenteText = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        diasLanzamientoText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("Duracion del dia (ms)");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        startProgram.setText("Iniciar");
        startProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startProgramActionPerformed(evt);
            }
        });

        jLabel1.setText("Productores");

        jLabel2.setText("Botones");

        jLabel3.setText("Pantallas");

        jLabel4.setText("P. Tactil");

        jLabel5.setText("Joystick");

        jLabel6.setText("Tarjeta SD");

        jLabel7.setText("Cant Producida");

        cantBotonesText.setText("0");

        cantPantallasText.setText("jLabel9");

        cantPTactilText.setText("jLabel10");

        cantJoystickText.setText("jLabel11");

        cantSDText.setText("jLabel12");

        jLabel8.setText("Cant Productor");

        cantProductorBotones.setText("jLabel9");
        cantProductorBotones.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cantProductorBotonesPropertyChange(evt);
            }
        });

        cantProductorPantalla.setText("jLabel9");

        cantProductorPTactil.setText("jLabel10");

        cantProductorJoystick.setText("jLabel11");

        cantProductorSD.setText("jLabel12");

        consolasTerminadasText.setText("jLabel9");

        jLabel9.setText("Consolas Terminadas:");

        jLabel10.setText("Cantidad Ensamblador");

        cantEnsambladorText.setText("jLabel11");

        jLabel11.setText("Status Jefe");

        statusJefeText.setText("jLabel12");

        jLabel12.setText("Status Gerente:");

        statusGerenteText.setText("jLabel13");

        jLabel13.setText("Dias para lanzamiento");

        diasLanzamientoText.setText("jLabel14");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(duracionDia, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(startProgram)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cantProductorBotones)
                                        .addComponent(cantProductorPantalla))
                                    .addComponent(cantProductorPTactil)
                                    .addComponent(cantProductorJoystick)
                                    .addComponent(cantProductorSD))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cantSDText)
                                        .addGap(21, 21, 21))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cantJoystickText)
                                            .addComponent(cantPTactilText)
                                            .addComponent(cantPantallasText)
                                            .addComponent(cantBotonesText))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cantEnsambladorText)
                                            .addComponent(consolasTerminadasText)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(statusJefeText)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statusGerenteText)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(diasLanzamientoText)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(duracionDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startProgram)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(statusJefeText)
                    .addComponent(jLabel12)
                    .addComponent(statusGerenteText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(diasLanzamientoText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cantBotonesText)
                            .addComponent(cantProductorBotones))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cantPantallasText)
                            .addComponent(cantProductorPantalla))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cantPTactilText)
                            .addComponent(cantProductorPTactil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cantJoystickText)
                            .addComponent(cantProductorJoystick))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cantEnsambladorText))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(consolasTerminadasText)
                            .addComponent(jLabel9))
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cantSDText)
                    .addComponent(cantProductorSD))
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void startProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startProgramActionPerformed
                        // TODO add your handling code here:
            statusJefeText.setText("Hola");
    }//GEN-LAST:event_startProgramActionPerformed

    private void cantProductorBotonesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cantProductorBotonesPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cantProductorBotonesPropertyChange

    /**
     * @param args the command line arguments
     */
     /*ELEMENTOS DEL MAIN*/
    public static volatile int contador_global = 0;
     /*la cantidad de botones que se estan generando */
    public static volatile int cantidad_botones = 0;
    
    /*Metodo que actualiza los labels */
    public static void setCantBotonesText(String text){
        cantBotonesText.setText(text);
    }
    
    public static void main(String args[]) {
        
        /*MOVI LOS ELEMENTOS DEL MAIN.JAVA PARA ACA*/
         
         
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelControl().setVisible(true);
            }
        });
        
        
        Semaphore mutex = new Semaphore(1);
        
        /*inicializamos el productor y el thread qeu actualiza los labels*/
        Refresher refresher = new Refresher(mutex);
        Productor_botones boton = new Productor_botones(mutex);
        boton.start();
        refresher.start();
        
        
    /**
     *
     */
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static volatile javax.swing.JLabel cantBotonesText;
    private javax.swing.JLabel cantEnsambladorText;
    private javax.swing.JLabel cantJoystickText;
    private javax.swing.JLabel cantPTactilText;
    private javax.swing.JLabel cantPantallasText;
    private javax.swing.JLabel cantProductorBotones;
    private javax.swing.JLabel cantProductorJoystick;
    private javax.swing.JLabel cantProductorPTactil;
    private javax.swing.JLabel cantProductorPantalla;
    private javax.swing.JLabel cantProductorSD;
    private javax.swing.JLabel cantSDText;
    private javax.swing.JLabel consolasTerminadasText;
    private javax.swing.JLabel diasLanzamientoText;
    private javax.swing.JSpinner duracionDia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton startProgram;
    private javax.swing.JLabel statusGerenteText;
    private javax.swing.JLabel statusJefeText;
    // End of variables declaration//GEN-END:variables
}
